# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vaibhav Kumbhar
email:
description: Software Engineer
twitter_username: username
github_username: vkumbhar94
minimal_mistakes_skin: default
search: true
excerpt_separator: "<!--more-->"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "GTM-NLK6G9NP"
    anonymize_ip: false

author:
  name: "Vaibhav Kumbhar"
  avatar: "/assets/images/bio_picture_cat.png"
  bio: "Backend Developer"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/beingvaibhav/"
    - label: "Medium"
      url: "https://medium.com/@vkumbhar94"
    - label: "GitHub"
      url: "https://github.com/vkumbhar94"
    #- label: "Tableau Public"
    #  url: "https://public.tableau.com/app/profile/yu.dong#!/"
    - label: "✅ My Weekly Vizzes"
      url: "https://vkumbhar94.github.io/personal-website/categories/#data-viz"
    - label: "✅ My Bi-Monthly Reading Notes"
      url: "https://vkumbhar94.github.io/personal-website/categories/#reading-notes"
    - label: "✅ My Blog Posts"
      url: "https://vkumbhar94.github.io/personal-website/categories/#blog"

footer:
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/beingvaibhav/"
    - label: "GitHub"
      url: "https://github.com/vkumbhar94"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      seo: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      seo: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
